build:
  cuda_version: "12.4.1"
  system_packages:
    - "ffmpeg"
  python_packages:
    - "accelerate==0.31.0"
    - "pydub==0.25.1"
    - "git+https://github.com/huggingface/parler-tts@8b8c576e2dbdc29172e30be7d68fac9357cd92c5#egg=parler-tts"
